/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/cXBFoBGbjgT
 */
import { CardHeader, CardContent, Card } from "@/components/ui/card"
import { Checkbox } from "@/components/ui/checkbox"
import { Button } from "@/components/ui/button"

export function MenuCart() {
  return (
    <Card>
      <CardHeader className="flex items-start">
        <h2 className="text-lg font-bold peer-disabled:cursor-not-allowed peer-disabled:opacity-70">Todo List</h2>
      </CardHeader>
      <CardContent className="flex flex-col p-0">
        <div className="border-t border-gray-200 dark:border-gray-800">
          <ul className="divide-y divide-gray-200 dark:divide-gray-800">
            <li className="flex items-center justify-between p-4">
              <div className="flex items-center space-x-4">
                <Checkbox className="peer-hidden" id="todo1" />
                <label
                  className="text-sm font-medium peer-disabled:cursor-not-allowed peer-disabled:opacity-70"
                  htmlFor="todo1"
                >
                  Add a new task
                </label>
              </div>
              <Button className="rounded-lg p-2" variant="ghost">
                <span className="sr-only">Delete</span>
              </Button>
            </li>
            <li className="flex items-center justify-between p-4">
              <div className="flex items-center space-x-4">
                <Checkbox className="peer-hidden" defaultChecked id="todo2" />
                <label
                  className="text-sm font-medium line-through peer-disabled:cursor-not-allowed peer-disabled:opacity-70"
                  htmlFor="todo2"
                >
                  Complete the tutorial
                </label>
              </div>
              <Button className="rounded-lg p-2" variant="ghost">
                <span className="sr-only">Delete</span>
              </Button>
            </li>
            <li className="flex items-center justify-between p-4">
              <div className="flex items-center space-x-4">
                <Checkbox className="peer-hidden" id="todo3" />
                <label
                  className="text-sm font-medium peer-disabled:cursor-not-allowed peer-disabled:opacity-70"
                  htmlFor="todo3"
                >
                  Walk the dog
                </label>
              </div>
              <Button className="rounded-lg p-2" variant="ghost">
                <span className="sr-only">Delete</span>
              </Button>
            </li>
          </ul>
        </div>
      </CardContent>
    </Card>
  )
}